/*
-- Query: SELECT * FROM edudb.member
LIMIT 0, 1000

-- Date: 2025-09-16 17:18
*/
INSERT INTO `member` (`USER_ID`,`USERNAME`,`PASSWORD`,`EMAIL`,`PHONE_NUMBER`,`PROFILE_IMAGE_URL`,`CREATED_AT`,`LAST_LOGIN_AT`,`LOGIN_FAIL_COUNT`,`ACCOUNT_LOCKED`) VALUES ('111','이오리','hashed_pw_111','user111@example.com',NULL,NULL,'2024-03-27 22:11:29',NULL,0,'N');
INSERT INTO `member` (`USER_ID`,`USERNAME`,`PASSWORD`,`EMAIL`,`PHONE_NUMBER`,`PROFILE_IMAGE_URL`,`CREATED_AT`,`LAST_LOGIN_AT`,`LOGIN_FAIL_COUNT`,`ACCOUNT_LOCKED`) VALUES ('112','b','b','user112@example.com',NULL,NULL,'2024-03-27 22:11:29',NULL,0,'N');
INSERT INTO `member` (`USER_ID`,`USERNAME`,`PASSWORD`,`EMAIL`,`PHONE_NUMBER`,`PROFILE_IMAGE_URL`,`CREATED_AT`,`LAST_LOGIN_AT`,`LOGIN_FAIL_COUNT`,`ACCOUNT_LOCKED`) VALUES ('200','a','a','user112@example.com',NULL,NULL,'2024-03-27 22:11:29',NULL,0,'N');
