--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-09-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "BOARD"."QNA" 
   (	"QNA_ID" NUMBER, 
	"TITLE" VARCHAR2(200 CHAR), 
	"CONTENT" CLOB, 
	"WRITER" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(200 CHAR), 
	"PASSWORD" VARCHAR2(200 CHAR), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index SYS_C008581
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD"."SYS_C008581" ON "BOARD"."QNA" ("QNA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger QNA_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOARD"."QNA_BEFORE_INSERT" 
BEFORE INSERT ON qna
FOR EACH ROW
BEGIN
    IF :NEW.qna_id IS NULL THEN
        SELECT qna_seq.NEXTVAL INTO :NEW.qna_id FROM dual;
    END IF;
END;

/
ALTER TRIGGER "BOARD"."QNA_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "BOARD"."QNA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."QNA" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."QNA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."QNA" ADD PRIMARY KEY ("QNA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
