--로그인시 USER_ID에 권한 부여 칼럼 추가
CREATE TABLE `member` (
  `USER_ID` varchar(50) NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `PROFILE_IMAGE_URL` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT NULL,
  `LAST_LOGIN_AT` date DEFAULT NULL,
  `LOGIN_FAIL_COUNT` int(11) DEFAULT '0',
  `ACCOUNT_LOCKED` char(1) DEFAULT 'N',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- 권한
CREATE TABLE `roles` (
  `ROLE_ID` int(11) NOT NULL,
  `ROLE_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- 멤버에 권한부여하는 테이블
CREATE TABLE `member_roles` (
  `USER_ID` varchar(50) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `ASSIGNED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `member_roles_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `member` (`USER_ID`),
  CONSTRAINT `member_roles_ibfk_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci